### ISSUE TITLE
element.setConfig is not a function

### ISSUE THREAD

**Issue by rpitera** [covrig/homeassistant-iframe-card#3]
Following instructions for Lovelace, I downloaded the lovelace-iframe.html file and copied it to config/www/custom_ui/.  Checked perms.  Added the following to my configuration.yaml:

```
frontend:
  extra_html_url:
  - /local/custom_ui/lovelace-iframe.html
```
Restarted hass.io and attempted to use the same example you provided as a test:

```
- type: "custom:lovelace-iframe"
  url: https://embed.windy.com/embed2.html?lat=48.234&lon=8.598&zoom=5&level=surface&overlay=radar&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=48.234&detailLon=8.598&metricWind=default&metricTemp=default&radarRange=-12
  height: 700
  title: WEATHER
  title-color: white
  title-background-color: darkgrey
  title-font-size: 15px
  title-font-weight: 500  
```

When I refresh I get the following error:

![clipboard01](https://user-images.githubusercontent.com/19910294/46546548-55ce4b00-c897-11e8-807a-029a722f8ca5.jpg)

I saw another user with the same issue in the forums.  Are we both missing something?

**Comment by covrig** [comment]
The lovelace element is different thing from this git. Follow the guide here to enable it: https://www.home-assistant.io/lovelace/iframe/. The settings are different.

Also, depending on your setup check this FAQ first https://www.home-assistant.io/lovelace/#faq.
Cheers.

**Comment by rpitera** [comment]
I know the difference between the stock iframe and this git.  I have no problem running the standard lovelace ui iframe card, nor anything else in lovelace.  

Except your card.  If you look closely at all of the information I provided, you can clearly see I am using your card.  Not the standard iframe card that is part of the production version of lovelace.

So I really don't need a pointer to the faq or the standard iframe docs.  That's not helpful.  So can you take a little closer look and answer the question?  Thanks.

**Comment by rpitera** [comment]
Have you had a chance to look at this?  I know custom-ui is installed properly and working as I am able to change other elements like icon_color.  But I still can't use this card.

**Comment by covrig** [comment]
I don't understand what are you trying to do. Why use my old lovelace version when there is an official one? My option is obsolete. I should remove it since it was already added to HASS.

If you use it outside of lovelace don't use the "custom:lovelace-iframe" one. Go for the  "custom_ui_state_card: state-card-iframe" option.

**Comment by rpitera** [comment]
I wanted to use your version because I was under the impression that it - as opposed to the standard lovelace iframe - could be styled; specifically the width and height.  If that is not the case (or due to lovelace changes, no longer the case) then I guess this can be closed.  The whole point of your approach was the styling, which the standard iframe lacks.

**Comment by covrig** [comment]
The width isn't configurable due to the restrictions of HASS. However for the official version, you can change the height with the scale option.
I can update this git to do what you want, but you will probably be the only user.

**Comment by rpitera** [comment]
Thanks but it doesn't make sense if you truly believe no one else would want this.
